// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw_NdNblwzoZbIoseLCPKBzm1rEsJbwcA',
    appId: '1:415872787031:web:8086c38600d052b972b912',
    messagingSenderId: '415872787031',
    projectId: 'buildingresume',
    authDomain: 'buildingresume.firebaseapp.com',
    storageBucket: 'buildingresume.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGJ6bkcxgTUXbUprpkqu00TYC5-k7f5kA',
    appId: '1:415872787031:android:a10271a4d16fe6ca72b912',
    messagingSenderId: '415872787031',
    projectId: 'buildingresume',
    storageBucket: 'buildingresume.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUtKRyruh8V-1j5Y9TDuBQ2x1gxnSCNq0',
    appId: '1:415872787031:ios:fb2bedbf8710505772b912',
    messagingSenderId: '415872787031',
    projectId: 'buildingresume',
    storageBucket: 'buildingresume.firebasestorage.app',
    androidClientId: '415872787031-haq6o5s06kjhrvmibjvfs4pbdp4gabcs.apps.googleusercontent.com',
    iosClientId: '415872787031-mlheipg0e197pg28kqs2lt9cgb605nvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.resume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUtKRyruh8V-1j5Y9TDuBQ2x1gxnSCNq0',
    appId: '1:415872787031:ios:fb2bedbf8710505772b912',
    messagingSenderId: '415872787031',
    projectId: 'buildingresume',
    storageBucket: 'buildingresume.firebasestorage.app',
    androidClientId: '415872787031-haq6o5s06kjhrvmibjvfs4pbdp4gabcs.apps.googleusercontent.com',
    iosClientId: '415872787031-mlheipg0e197pg28kqs2lt9cgb605nvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.resume',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw_NdNblwzoZbIoseLCPKBzm1rEsJbwcA',
    appId: '1:415872787031:web:cd95f025fe7c506572b912',
    messagingSenderId: '415872787031',
    projectId: 'buildingresume',
    authDomain: 'buildingresume.firebaseapp.com',
    storageBucket: 'buildingresume.firebasestorage.app',
  );
}
